package com.example.remitlyintern.Utils;

import java.util.HashMap;
import java.util.Map;

public class CountryISO2Map {

    public static final HashMap<String, String> countryIsoToCountryMap = createCountryISO2Map();

    private static HashMap<String,String> createCountryISO2Map() {
        HashMap<String, String> countryIsoToCountryMap = new HashMap<String, String>();
        countryIsoToCountryMap.put("AD", "Andorra, Principality Of");
        countryIsoToCountryMap.put("AE", "United Arab Emirates");
        countryIsoToCountryMap.put("AF", "Afghanistan, Islamic State Of");
        countryIsoToCountryMap.put("AG", "Antigua And Barbuda");
        countryIsoToCountryMap.put("AI", "Anguilla");
        countryIsoToCountryMap.put("AL", "Albania");
        countryIsoToCountryMap.put("AM", "Armenia");
        countryIsoToCountryMap.put("AN", "Netherlands Antilles");
        countryIsoToCountryMap.put("AO", "Angola");
        countryIsoToCountryMap.put("AQ", "Antarctica");
        countryIsoToCountryMap.put("AR", "Argentina");
        countryIsoToCountryMap.put("AS", "American Samoa");
        countryIsoToCountryMap.put("AT", "Austria");
        countryIsoToCountryMap.put("AU", "Australia");
        countryIsoToCountryMap.put("AW", "Aruba");
        countryIsoToCountryMap.put("AZ", "Azerbaidjan");
        countryIsoToCountryMap.put("BA", "Bosnia-Herzegovina");
        countryIsoToCountryMap.put("BB", "Barbados");
        countryIsoToCountryMap.put("BD", "Bangladesh");
        countryIsoToCountryMap.put("BE", "Belgium");
        countryIsoToCountryMap.put("BF", "Burkina Faso");
        countryIsoToCountryMap.put("BG", "Bulgaria");
        countryIsoToCountryMap.put("BH", "Bahrain");
        countryIsoToCountryMap.put("BI", "Burundi");
        countryIsoToCountryMap.put("BJ", "Benin");
        countryIsoToCountryMap.put("BM", "Bermuda");
        countryIsoToCountryMap.put("BN", "Brunei Darussalam");
        countryIsoToCountryMap.put("BO", "Bolivia");
        countryIsoToCountryMap.put("BR", "Brazil");
        countryIsoToCountryMap.put("BS", "Bahamas");
        countryIsoToCountryMap.put("BT", "Bhutan");
        countryIsoToCountryMap.put("BV", "Bouvet Island");
        countryIsoToCountryMap.put("BW", "Botswana");
        countryIsoToCountryMap.put("BY", "Belarus");
        countryIsoToCountryMap.put("BZ", "Belize");
        countryIsoToCountryMap.put("CA", "Canada");
        countryIsoToCountryMap.put("CC", "Cocos (Keeling) Islands");
        countryIsoToCountryMap.put("CF", "Central African Republic");
        countryIsoToCountryMap.put("CD", "Congo, The Democratic Republic Of The");
        countryIsoToCountryMap.put("CG", "Congo");
        countryIsoToCountryMap.put("CH", "Switzerland");
        countryIsoToCountryMap.put("CI", "Ivory Coast (Cote D'Ivoire)");
        countryIsoToCountryMap.put("CK", "Cook Islands");
        countryIsoToCountryMap.put("CL", "Chile");
        countryIsoToCountryMap.put("CM", "Cameroon");
        countryIsoToCountryMap.put("CN", "China");
        countryIsoToCountryMap.put("CO", "Colombia");
        countryIsoToCountryMap.put("CR", "Costa Rica");
        countryIsoToCountryMap.put("CS", "Former Czechoslovakia");
        countryIsoToCountryMap.put("CU", "Cuba");
        countryIsoToCountryMap.put("CV", "Cape Verde");
        countryIsoToCountryMap.put("CX", "Christmas Island");
        countryIsoToCountryMap.put("CY", "Cyprus");
        countryIsoToCountryMap.put("CZ", "Czech Republic");
        countryIsoToCountryMap.put("DE", "Germany");
        countryIsoToCountryMap.put("DJ", "Djibouti");
        countryIsoToCountryMap.put("DK", "Denmark");
        countryIsoToCountryMap.put("DM", "Dominica");
        countryIsoToCountryMap.put("DO", "Dominican Republic");
        countryIsoToCountryMap.put("DZ", "Algeria");
        countryIsoToCountryMap.put("EC", "Ecuador");
        countryIsoToCountryMap.put("EE", "Estonia");
        countryIsoToCountryMap.put("EG", "Egypt");
        countryIsoToCountryMap.put("EH", "Western Sahara");
        countryIsoToCountryMap.put("ER", "Eritrea");
        countryIsoToCountryMap.put("ES", "Spain");
        countryIsoToCountryMap.put("ET", "Ethiopia");
        countryIsoToCountryMap.put("FI", "Finland");
        countryIsoToCountryMap.put("FJ", "Fiji");
        countryIsoToCountryMap.put("FK", "Falkland Islands");
        countryIsoToCountryMap.put("FM", "Micronesia");
        countryIsoToCountryMap.put("FO", "Faroe Islands");
        countryIsoToCountryMap.put("FR", "France");
        countryIsoToCountryMap.put("FX", "France (European Territory)");
        countryIsoToCountryMap.put("GA", "Gabon");
        countryIsoToCountryMap.put("UK", "Great Britain");
        countryIsoToCountryMap.put("GD", "Grenada");
        countryIsoToCountryMap.put("GE", "Georgia");
        countryIsoToCountryMap.put("GF", "French Guyana");
        countryIsoToCountryMap.put("GH", "Ghana");
        countryIsoToCountryMap.put("GI", "Gibraltar");
        countryIsoToCountryMap.put("GL", "Greenland");
        countryIsoToCountryMap.put("GM", "Gambia");
        countryIsoToCountryMap.put("GN", "Guinea");
        countryIsoToCountryMap.put("GP", "Guadeloupe (French)");
        countryIsoToCountryMap.put("GQ", "Equatorial Guinea");
        countryIsoToCountryMap.put("GR", "Greece");
        countryIsoToCountryMap.put("GS", "S. Georgia & S. Sandwich Isls.");
        countryIsoToCountryMap.put("GT", "Guatemala");
        countryIsoToCountryMap.put("GU", "Guam (USA)");
        countryIsoToCountryMap.put("GW", "Guinea Bissau");
        countryIsoToCountryMap.put("GY", "Guyana");
        countryIsoToCountryMap.put("HK", "Hong Kong");
        countryIsoToCountryMap.put("HM", "Heard And McDonald Islands");
        countryIsoToCountryMap.put("HN", "Honduras");
        countryIsoToCountryMap.put("HR", "Croatia");
        countryIsoToCountryMap.put("HT", "Haiti");
        countryIsoToCountryMap.put("HU", "Hungary");
        countryIsoToCountryMap.put("ID", "Indonesia");
        countryIsoToCountryMap.put("IE", "Ireland");
        countryIsoToCountryMap.put("IL", "Israel");
        countryIsoToCountryMap.put("IN", "India");
        countryIsoToCountryMap.put("IO", "British Indian Ocean Territory");
        countryIsoToCountryMap.put("IQ", "Iraq");
        countryIsoToCountryMap.put("IR", "Iran");
        countryIsoToCountryMap.put("IS", "Iceland");
        countryIsoToCountryMap.put("IT", "Italy");
        countryIsoToCountryMap.put("JM", "Jamaica");
        countryIsoToCountryMap.put("JO", "Jordan");
        countryIsoToCountryMap.put("JP", "Japan");
        countryIsoToCountryMap.put("KE", "Kenya");
        countryIsoToCountryMap.put("KG", "Kyrgyz Republic (Kyrgyzstan)");
        countryIsoToCountryMap.put("KH", "Cambodia, Kingdom Of");
        countryIsoToCountryMap.put("KI", "Kiribati");
        countryIsoToCountryMap.put("KM", "Comoros");
        countryIsoToCountryMap.put("KN", "Saint Kitts & Nevis Anguilla");
        countryIsoToCountryMap.put("KP", "North Korea");
        countryIsoToCountryMap.put("KR", "South Korea");
        countryIsoToCountryMap.put("KW", "Kuwait");
        countryIsoToCountryMap.put("KY", "Cayman Islands");
        countryIsoToCountryMap.put("KZ", "Kazakhstan");
        countryIsoToCountryMap.put("LA", "Laos");
        countryIsoToCountryMap.put("LB", "Lebanon");
        countryIsoToCountryMap.put("LC", "Saint Lucia");
        countryIsoToCountryMap.put("LI", "Liechtenstein");
        countryIsoToCountryMap.put("LK", "Sri Lanka");
        countryIsoToCountryMap.put("LR", "Liberia");
        countryIsoToCountryMap.put("LS", "Lesotho");
        countryIsoToCountryMap.put("LT", "Lithuania");
        countryIsoToCountryMap.put("LU", "Luxembourg");
        countryIsoToCountryMap.put("LV", "Latvia");
        countryIsoToCountryMap.put("LY", "Libya");
        countryIsoToCountryMap.put("MA", "Morocco");
        countryIsoToCountryMap.put("MC", "Monaco");
        countryIsoToCountryMap.put("MD", "Moldavia");
        countryIsoToCountryMap.put("MG", "Madagascar");
        countryIsoToCountryMap.put("MH", "Marshall Islands");
        countryIsoToCountryMap.put("MK", "Macedonia");
        countryIsoToCountryMap.put("ML", "Mali");
        countryIsoToCountryMap.put("MM", "Myanmar");
        countryIsoToCountryMap.put("MN", "Mongolia");
        countryIsoToCountryMap.put("MO", "Macau");
        countryIsoToCountryMap.put("MP", "Northern Mariana Islands");
        countryIsoToCountryMap.put("MQ", "Martinique (French)");
        countryIsoToCountryMap.put("MR", "Mauritania");
        countryIsoToCountryMap.put("MS", "Montserrat");
        countryIsoToCountryMap.put("MT", "Malta");
        countryIsoToCountryMap.put("MU", "Mauritius");
        countryIsoToCountryMap.put("MV", "Maldives");
        countryIsoToCountryMap.put("MW", "Malawi");
        countryIsoToCountryMap.put("MX", "Mexico");
        countryIsoToCountryMap.put("MY", "Malaysia");
        countryIsoToCountryMap.put("MZ", "Mozambique");
        countryIsoToCountryMap.put("NA", "Namibia");
        countryIsoToCountryMap.put("NC", "New Caledonia (French)");
        countryIsoToCountryMap.put("NE", "Niger");
        countryIsoToCountryMap.put("NF", "Norfolk Island");
        countryIsoToCountryMap.put("NG", "Nigeria");
        countryIsoToCountryMap.put("NI", "Nicaragua");
        countryIsoToCountryMap.put("NL", "Netherlands");
        countryIsoToCountryMap.put("NO", "Norway");
        countryIsoToCountryMap.put("NP", "Nepal");
        countryIsoToCountryMap.put("NR", "Nauru");
        countryIsoToCountryMap.put("NT", "Neutral Zone");
        countryIsoToCountryMap.put("NU", "Niue");
        countryIsoToCountryMap.put("NZ", "New Zealand");
        countryIsoToCountryMap.put("OM", "Oman");
        countryIsoToCountryMap.put("PA", "Panama");
        countryIsoToCountryMap.put("PE", "Peru");
        countryIsoToCountryMap.put("PF", "Polynesia (French)");
        countryIsoToCountryMap.put("PG", "Papua New Guinea");
        countryIsoToCountryMap.put("PH", "Philippines");
        countryIsoToCountryMap.put("PK", "Pakistan");
        countryIsoToCountryMap.put("PL", "Poland");
        countryIsoToCountryMap.put("PM", "Saint Pierre And Miquelon");
        countryIsoToCountryMap.put("PN", "Pitcairn Island");
        countryIsoToCountryMap.put("PR", "Puerto Rico");
        countryIsoToCountryMap.put("PT", "Portugal");
        countryIsoToCountryMap.put("PW", "Palau");
        countryIsoToCountryMap.put("PY", "Paraguay");
        countryIsoToCountryMap.put("QA", "Qatar");
        countryIsoToCountryMap.put("RE", "Reunion (French)");
        countryIsoToCountryMap.put("RO", "Romania");
        countryIsoToCountryMap.put("RU", "Russian Federation");
        countryIsoToCountryMap.put("RW", "Rwanda");
        countryIsoToCountryMap.put("SA", "Saudi Arabia");
        countryIsoToCountryMap.put("SB", "Solomon Islands");
        countryIsoToCountryMap.put("SC", "Seychelles");
        countryIsoToCountryMap.put("SD", "Sudan");
        countryIsoToCountryMap.put("SE", "Sweden");
        countryIsoToCountryMap.put("SG", "Singapore");
        countryIsoToCountryMap.put("SH", "Saint Helena");
        countryIsoToCountryMap.put("SI", "Slovenia");
        countryIsoToCountryMap.put("SJ", "Svalbard And Jan Mayen Islands");
        countryIsoToCountryMap.put("SK", "Slovak Republic");
        countryIsoToCountryMap.put("SL", "Sierra Leone");
        countryIsoToCountryMap.put("SM", "San Marino");
        countryIsoToCountryMap.put("SN", "Senegal");
        countryIsoToCountryMap.put("SO", "Somalia");
        countryIsoToCountryMap.put("SR", "Suriname");
        countryIsoToCountryMap.put("ST", "Saint Tome (Sao Tome) And Principe");
        countryIsoToCountryMap.put("SU", "Former USSR");
        countryIsoToCountryMap.put("SV", "El Salvador");
        countryIsoToCountryMap.put("SY", "Syria");
        countryIsoToCountryMap.put("SZ", "Swaziland");
        countryIsoToCountryMap.put("TC", "Turks And Caicos Islands");
        countryIsoToCountryMap.put("TD", "Chad");
        countryIsoToCountryMap.put("TF", "French Southern Territories");
        countryIsoToCountryMap.put("TG", "Togo");
        countryIsoToCountryMap.put("TH", "Thailand");
        countryIsoToCountryMap.put("TJ", "Tadjikistan");
        countryIsoToCountryMap.put("TK", "Tokelau");
        countryIsoToCountryMap.put("TM", "Turkmenistan");
        countryIsoToCountryMap.put("TN", "Tunisia");
        countryIsoToCountryMap.put("TO", "Tonga");
        countryIsoToCountryMap.put("TP", "East Timor");
        countryIsoToCountryMap.put("TR", "Turkey");
        countryIsoToCountryMap.put("TT", "Trinidad And Tobago");
        countryIsoToCountryMap.put("TV", "Tuvalu");
        countryIsoToCountryMap.put("TW", "Taiwan");
        countryIsoToCountryMap.put("TZ", "Tanzania");
        countryIsoToCountryMap.put("UA", "Ukraine");
        countryIsoToCountryMap.put("UG", "Uganda");
        countryIsoToCountryMap.put("UM", "USA Minor Outlying Islands");
        countryIsoToCountryMap.put("US", "United States");
        countryIsoToCountryMap.put("UY", "Uruguay");
        countryIsoToCountryMap.put("UZ", "Uzbekistan");
        countryIsoToCountryMap.put("VA", "Holy See (Vatican City State)");
        countryIsoToCountryMap.put("VC", "Saint Vincent & Grenadines");
        countryIsoToCountryMap.put("VE", "Venezuela");
        countryIsoToCountryMap.put("VG", "Virgin Islands (British)");
        countryIsoToCountryMap.put("VI", "Virgin Islands (USA)");
        countryIsoToCountryMap.put("VN", "Vietnam");
        countryIsoToCountryMap.put("VU", "Vanuatu");
        countryIsoToCountryMap.put("WF", "Wallis And Futuna Islands");
        countryIsoToCountryMap.put("WS", "Samoa");
        countryIsoToCountryMap.put("YE", "Yemen");
        countryIsoToCountryMap.put("YT", "Mayotte");
        countryIsoToCountryMap.put("YU", "Yugoslavia");
        countryIsoToCountryMap.put("ZA", "South Africa");
        countryIsoToCountryMap.put("ZM", "Zambia");
        countryIsoToCountryMap.put("ZR", "Zaire");
        countryIsoToCountryMap.put("ZW", "Zimbabwe");
        return countryIsoToCountryMap;
    }
}
